In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

<h3>Preparing the data<h3>

In [2]:
train_data = pd.read_csv('data_train.csv')
train = train_data[:182649] #no need to print

In [3]:
train.info() #Check for null, if there are null - use dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182649 entries, 0 to 182648
Data columns (total 25 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Id                    182649 non-null  int64
 1   HighBP                182649 non-null  int64
 2   HighChol              182649 non-null  int64
 3   CholCheck             182649 non-null  int64
 4   BMI                   182649 non-null  int64
 5   Smoker                182649 non-null  int64
 6   Stroke                182649 non-null  int64
 7   HeartDiseaseorAttack  182649 non-null  int64
 8   PhysActivity          182649 non-null  int64
 9   Fruits                182649 non-null  int64
 10  Veggies               182649 non-null  int64
 11  HvyAlcoholConsump     182649 non-null  int64
 12  AnyHealthcare         182649 non-null  int64
 13  NoDocbcCost           182649 non-null  int64
 14  GenHlth               182649 non-null  int64
 15  MentHlth              182649 non-n

<h3>Split into input & output<h3>

In [4]:
X = train.drop(columns=['Status'])
y = train['Status']

In [5]:
y.describe()

count    182649.000000
mean          0.175347
std           0.380265
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Status, dtype: float64

<h3>Prepare the test set<h3>

In [6]:
test = train_data[182650:202944]
test

Id  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
182650  182650       1         1          1   26       1       0   
182651  182651       1         0          1   35       0       0   
182652  182652       1         0          1   30       0       0   
182653  182653       1         1          1   24       1       0   
182654  182654       0         0          1   20       1       0   
...        ...     ...       ...        ...  ...     ...     ...   
202939  202939       0         0          1   29       0       0   
202940  202940       0         0          1   23       0       0   
202941  202941       1         1          1   38       0       0   
202942  202942       0         1          1   22       0       0   
202943  202943       0         0          1   22       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  MentHlth  PhysHlth  \
182650                     0             0       1  ...         0         0   
182651                     0             0       0  ...         0         0   
182652                     0             1       0  ...         0         0   
182653                     0             1       0  ...        15         8   
182654                     0             0       0  ...         0         3   
...                      ...           ...     ...  ...       ...       ...   
202939                     0             1       0  ...        10         2   
202940                     0             1       0  ...         0         0   
202941                     0             1       1  ...         0         2   
202942                     0             1       1  ...         0        14   
202943                     0             0       0  ...         2         2   

        DiffWalk  Sex  Age  Education  Income  ExtraMedTest  ExtraAlcoholTest  \
182650         0    0    7          6       8            28               100   
182651         1    0   11          4       7            31                64   
182652         0    1    5          5       8           -11                -3   
182653         0    0    9          4       6           -94                 0   
182654         0    0    9          4       6           -38              -140   
...          ...  ...  ...        ...     ...           ...               ...   
202939         0    0    8          6       7           -66                 4   
202940         0    0   11          5       7             0               -84   
202941         0    1   10          6       6           -57               -16   
202942         0    0    9          6       7            59                 0   
202943         0    1    5          6       8           -96                 0   

        Status  
182650       1  
182651       1  
182652       0  
182653       0  
182654       0  
...        ...  
202939       0  
202940       0  
202941       0  
202942       0  
202943       0  

[20294 rows x 25 columns]

<h3>Split data into train and test<h3>

In [7]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_test = test.drop(columns=['Status'])
y_test = test['Status']

In [8]:
y_test[:10]

182650    1
182651    1
182652    0
182653    0
182654    0
182655    0
182656    0
182657    1
182658    1
182659    0
Name: Status, dtype: int64

<h3>Decision Trees<h3>

In [9]:
from sklearn.tree import DecisionTreeClassifier

# Train model
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)

In [10]:
y_pred_tree[:10]

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int64)

<h3>Evaluate Model<h3>

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_tree)
print("Accuracy:", accuracy)

Accuracy: 0.8739528924805361


In [12]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_test, y_pred_tree))

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.88      0.92     16690
           1       0.60      0.84      0.70      3604

    accuracy                           0.87     20294
   macro avg       0.78      0.86      0.81     20294
weighted avg       0.90      0.87      0.88     20294



In [13]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_tree))

Confusion Matrix:
[[14698  1992]
 [  566  3038]]


<h3>Random Forest<h3>

In [14]:
from sklearn.ensemble import RandomForestClassifier

# Train model
frst_model = RandomForestClassifier()
frst_model.fit(X_train, y_train)

y_pred_frst = frst_model.predict(X_test)

In [15]:
y_pred_frst[:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

<h3>Evaluate Model<h3>

In [16]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_frst)
print("Accuracy:", accuracy)

Accuracy: 0.9568838080220755


In [17]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_test, y_pred_frst))

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97     16690
           1       0.97      0.78      0.87      3604

    accuracy                           0.96     20294
   macro avg       0.96      0.89      0.92     20294
weighted avg       0.96      0.96      0.96     20294



In [18]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_frst))

Confusion Matrix:
[[16602    88]
 [  787  2817]]


<h3>Linear Regression<h3>

In [20]:
from sklearn.linear_model import LinearRegression

# Train model
rgs_model = LinearRegression()
rgs_model.fit(X_train, y_train)

y_pred_rgs = rgs_model.predict(X_test)

In [22]:
threshold = 0.5
y_pred_rgs = [1 if pred > threshold else 0 for pred in y_pred_rgs]
y_pred_rgs[:10]

[0, 0, 0, 0, 0, 0, 0, 1, 0, 1]

<h3>Evaluate Model<h3>

In [23]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_rgs)
print("Accuracy:", accuracy)

Accuracy: 0.9192372129693506


In [24]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_test, y_pred_rgs))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     16690
           1       0.93      0.59      0.72      3604

    accuracy                           0.92     20294
   macro avg       0.92      0.79      0.84     20294
weighted avg       0.92      0.92      0.91     20294



In [25]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rgs))

Confusion Matrix:
[[16533   157]
 [ 1482  2122]]
