In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

<h3>Preparing the train data<h3>

In [26]:
train_data = pd.read_csv('data_train.csv')
train = train_data[:int(len(train_data)*0.6)] #no need to print

In [27]:
train.info() #Check for null, if there are null - use dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121766 entries, 0 to 121765
Data columns (total 25 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Id                    121766 non-null  int64
 1   HighBP                121766 non-null  int64
 2   HighChol              121766 non-null  int64
 3   CholCheck             121766 non-null  int64
 4   BMI                   121766 non-null  int64
 5   Smoker                121766 non-null  int64
 6   Stroke                121766 non-null  int64
 7   HeartDiseaseorAttack  121766 non-null  int64
 8   PhysActivity          121766 non-null  int64
 9   Fruits                121766 non-null  int64
 10  Veggies               121766 non-null  int64
 11  HvyAlcoholConsump     121766 non-null  int64
 12  AnyHealthcare         121766 non-null  int64
 13  NoDocbcCost           121766 non-null  int64
 14  GenHlth               121766 non-null  int64
 15  MentHlth              121766 non-n

<h3>Split into input & output<h3>

In [28]:
X = train.drop(columns=['Status'])
y = train['Status']

In [29]:
y.describe()

count    121766.000000
mean          0.174589
std           0.379617
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Status, dtype: float64

<h3>Prepare the validation data<h3>

In [30]:
val = train_data[int(len(train_data)*0.6):int(len(train_data)*0.8)]
val

Id  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
121766  121766       0         0          1   22       1       0   
121767  121767       0         0          1   28       0       0   
121768  121768       0         0          1   22       1       0   
121769  121769       0         0          1   23       1       0   
121770  121770       1         1          1   23       1       0   
...        ...     ...       ...        ...  ...     ...     ...   
162350  162350       1         0          1   35       0       0   
162351  162351       0         0          0   23       1       0   
162352  162352       0         1          1   25       0       0   
162353  162353       1         0          1   27       1       0   
162354  162354       0         0          1   26       1       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  MentHlth  PhysHlth  \
121766                     0             1       1  ...         0         1   
121767                     0             1       1  ...         0         0   
121768                     0             1       1  ...         5         2   
121769                     0             1       1  ...         0         0   
121770                     0             1       1  ...         0         0   
...                      ...           ...     ...  ...       ...       ...   
162350                     0             0       1  ...         0         0   
162351                     0             1       1  ...         0         0   
162352                     0             1       1  ...         0         0   
162353                     0             0       1  ...         0         2   
162354                     0             1       1  ...         0         0   

        DiffWalk  Sex  Age  Education  Income  ExtraMedTest  ExtraAlcoholTest  \
121766         0    0   11          4       8          -152               -89   
121767         0    1    8          6       7          -117               -68   
121768         0    0    3          4       8            49              -187   
121769         0    1   12          5       5           -46                 0   
121770         0    1    1          4       1            83                78   
...          ...  ...  ...        ...     ...           ...               ...   
162350         0    1    9          6       7           -73                 0   
162351         0    1    5          4       8            26                 0   
162352         0    1   12          6       8           -18               -47   
162353         1    0   12          5       7           100               119   
162354         0    0    4          6       8           -30                47   

        Status  
121766       0  
121767       0  
121768       0  
121769       0  
121770       0  
...        ...  
162350       0  
162351       0  
162352       0  
162353       1  
162354       0  

[40589 rows x 25 columns]

<h3>Prepare the test set<h3>

In [31]:
test = train_data[int(len(train_data)*0.8):len(train_data)]
test

Id  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
162355  162355       0         0          1   29       1       0   
162356  162356       1         1          1   33       0       0   
162357  162357       0         0          1   39       0       0   
162358  162358       0         0          1   20       0       0   
162359  162359       0         0          1   23       0       0   
...        ...     ...       ...        ...  ...     ...     ...   
202939  202939       0         0          1   29       0       0   
202940  202940       0         0          1   23       0       0   
202941  202941       1         1          1   38       0       0   
202942  202942       0         1          1   22       0       0   
202943  202943       0         0          1   22       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  MentHlth  PhysHlth  \
162355                     0             1       1  ...         0         0   
162356                     1             0       1  ...         0         3   
162357                     0             1       1  ...         5        30   
162358                     0             1       1  ...         0         0   
162359                     0             1       1  ...         0         0   
...                      ...           ...     ...  ...       ...       ...   
202939                     0             1       0  ...        10         2   
202940                     0             1       0  ...         0         0   
202941                     0             1       1  ...         0         2   
202942                     0             1       1  ...         0        14   
202943                     0             0       0  ...         2         2   

        DiffWalk  Sex  Age  Education  Income  ExtraMedTest  ExtraAlcoholTest  \
162355         0    0   11          6       5            14                 0   
162356         0    0    9          5       7           -58               -70   
162357         0    0    5          5       8            89               -72   
162358         0    0    7          6       8             0               -64   
162359         0    0    7          6       8           -24              -179   
...          ...  ...  ...        ...     ...           ...               ...   
202939         0    0    8          6       7           -66                 4   
202940         0    0   11          5       7             0               -84   
202941         0    1   10          6       6           -57               -16   
202942         0    0    9          6       7            59                 0   
202943         0    1    5          6       8           -96                 0   

        Status  
162355       0  
162356       0  
162357       0  
162358       0  
162359       0  
...        ...  
202939       0  
202940       0  
202941       0  
202942       0  
202943       0  

[40589 rows x 25 columns]

<h3>Split data into train and validation set<h3>

In [32]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
X_val = val.drop(columns=['Status'])
y_val = val['Status']

In [33]:
y_val[:10]

121766    0
121767    0
121768    0
121769    0
121770    0
121771    0
121772    0
121773    0
121774    0
121775    0
Name: Status, dtype: int64

<h3>Decision Trees<h3>

In [34]:
from sklearn.tree import DecisionTreeClassifier

# Train model
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_val)

In [35]:
y_pred_tree[:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

<h3>Validate Model<h3>

In [36]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val, y_pred_tree)
print("Accuracy:", accuracy)

Accuracy: 0.8985932149104437


In [37]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_val, y_pred_tree))

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.91      0.94     33395
           1       0.67      0.85      0.75      7194

    accuracy                           0.90     40589
   macro avg       0.82      0.88      0.84     40589
weighted avg       0.91      0.90      0.90     40589



In [38]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred_tree))

Confusion Matrix:
[[30324  3071]
 [ 1045  6149]]


<h3>Random Forest<h3>

In [39]:
from sklearn.ensemble import RandomForestClassifier

# Train model
frst_model = RandomForestClassifier()
frst_model.fit(X_train, y_train)

y_pred_frst = frst_model.predict(X_val)

In [40]:
y_pred_frst[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

<h3>Validate Model<h3>

In [41]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val, y_pred_frst)
print("Accuracy:", accuracy)

Accuracy: 0.9588558476434502


In [42]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_val, y_pred_frst))

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98     33395
           1       0.97      0.79      0.87      7194

    accuracy                           0.96     40589
   macro avg       0.96      0.89      0.92     40589
weighted avg       0.96      0.96      0.96     40589



In [43]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred_frst))

Confusion Matrix:
[[33237   158]
 [ 1512  5682]]


<h3>Linear Regression<h3>

In [44]:
from sklearn.linear_model import LinearRegression

# Train model
rgs_model = LinearRegression()
rgs_model.fit(X_train, y_train)

y_pred_rgs = rgs_model.predict(X_val)

In [45]:
threshold = 0.5
y_pred_rgs = [1 if pred > threshold else 0 for pred in y_pred_rgs]
y_pred_rgs[:10]

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

<h3>Validate Model<h3>

In [46]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val, y_pred_rgs)
print("Accuracy:", accuracy)

Accuracy: 0.9217275616546355


In [47]:
from sklearn.metrics import classification_report
print("Classification Report:")
print(classification_report(y_val, y_pred_rgs))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     33395
           1       0.93      0.60      0.73      7194

    accuracy                           0.92     40589
   macro avg       0.93      0.80      0.84     40589
weighted avg       0.92      0.92      0.91     40589



In [49]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred_rgs))

Confusion Matrix:
[[33091   304]
 [ 2873  4321]]
